// String constants for IPC channels. Centralized so both main and preload
// share the same list and a typo can't silently create a dead channel.

export const GIT = {
  OPEN_REPO: "git:open-repo",
  CURRENT_REPO: "git:current-repo",
  STATUS: "git:status",
  COMMIT: "git:commit",
  STAGE: "git:stage",
  UNSTAGE: "git:unstage",
  STAGE_PATCH: "git:stage-patch",
  UNSTAGE_PATCH: "git:unstage-patch",
  DISCARD_PATCH: "git:discard-patch",
  DISCARD: "git:discard",
  DIFF: "git:diff",
  DIFF_STAGED: "git:diff-staged",
  LOG: "git:log",
  BRANCHES: "git:branches",
  BRANCH_CREATE: "git:branch-create",
  BRANCH_DELETE: "git:branch-delete",
  BRANCH_RENAME: "git:branch-rename",
  BRANCH_SET_UPSTREAM: "git:branch-set-upstream",
  CHECKOUT: "git:checkout",
  CHECKOUT_CREATE: "git:checkout-create",
  MERGE: "git:merge",
  REBASE: "git:rebase",
  REBASE_CONTINUE: "git:rebase-continue",
  REBASE_ABORT: "git:rebase-abort",
  REBASE_SKIP: "git:rebase-skip",
  MERGE_ABORT: "git:merge-abort",
  PULL: "git:pull",
  PUSH: "git:push",
  FETCH: "git:fetch",
  PULL_BRANCH: "git:pull-branch",
  PUSH_BRANCH: "git:push-branch",
  REMOTES: "git:remotes",
  REMOTE_ADD: "git:remote-add",
  REMOTE_REMOVE: "git:remote-remove",
  REMOTE_SET_URL: "git:remote-set-url",
  CONFIG_LIST: "git:config-list",
  CONFIG_GET: "git:config-get",
  CONFIG_SET: "git:config-set",
  FILE_AT_REF: "git:file-at-ref",
  WRITE_FILE: "git:write-file",
  CHERRY_PICK: "git:cherry-pick",
  REVERT: "git:revert",
  RESET: "git:reset",
  STASH: "git:stash",
  STASH_POP: "git:stash-pop",
  STASH_LIST: "git:stash-list",
  STASH_APPLY: "git:stash-apply",
  STASH_DROP: "git:stash-drop",
  STASH_SHOW: "git:stash-show",
  STASH_SHOW_FILES: "git:stash-show-files",
  TAGS: "git:tags",
  TAG_CREATE: "git:tag-create",
  TAG_DELETE: "git:tag-delete",
  WORKTREE_LIST: "git:worktree-list",
  WORKTREE_ADD: "git:worktree-add",
  WORKTREE_REMOVE: "git:worktree-remove",
  WORKTREE_LOCK: "git:worktree-lock",
  WORKTREE_UNLOCK: "git:worktree-unlock",
  COMMIT_FILES: "git:commit-files",
  MARK_RESOLVED: "git:mark-resolved",
  SHOW_OPEN_DIALOG: "git:show-open-dialog",
  OPEN_EXTERNAL: "git:open-external",
  RECENT_REPOS: "git:recent-repos",
  CLOSE_REPO: "git:close-repo",
  SET_ACTIVE_REPO: "git:set-active-repo",
  OPEN_REPOS: "git:open-repos",
  SESSION_GET: "git:session-get",
  SESSION_SET: "git:session-set",
} as const;

export const GH = {
  AVAILABLE: "gh:available",
  PR_LIST: "gh:pr-list",
  PR_VIEW: "gh:pr-view",
  PR_CREATE: "gh:pr-create",
  PR_MERGE: "gh:pr-merge",
  PR_CHECKS: "gh:pr-checks",
  PR_REVIEW: "gh:pr-review",
  REPO_INFO: "gh:repo-info",
  COLLABORATORS: "gh:collaborators",
} as const;

export const EVENTS = {
  REPO_CHANGED: "repo:changed",
  FETCH_COMPLETE: "fetch:complete",
  GIT_PROGRESS: "git:progress",
} as const;
